GEMINI_API_KEY =[\"AIzaSyC_z4VKUSMQF_IRJlFo7YTow4f7L30l41I"] # Referencia a Streamlit Secrets
gemini.configure("AIzaSyC_z4VKUSMQF_IRJlFo7YTow4f7L30l41I")
GOOGLE_APPLICATION_CREDENTIALS='botidinamix-g.json
